### ISSUE TITLE
Issue with different size of superpixel

### ISSUE THREAD

**Issue by fderue** [carlren/gSLIC2#7]
Hello, 

I tried gSLICr by specifying different size of superpixel :
- For spixel_size = 10, it results in a strange segmentation like on the picture [slic_size10] , with totally squared spixel. Is it supposed to work only with specific spixel_size? 
- For spixel_size = 50, there are still "orphan" superpixels as we can see on image [slic_size50]. Is the function "do_enforce_connectivity" not supposed to remove them? 
  
  I have tried with other images and other machines but the problem seems recurrent.

![slic_size10](https://cloud.githubusercontent.com/assets/10605043/12559141/45e1db00-c361-11e5-9658-e7fb881ec0d5.png)
![slic_size50](https://cloud.githubusercontent.com/assets/10605043/12559140/45dd65fc-c361-11e5-8c1c-c8ec87670419.png)

**Comment by carlren** [comment]
Hi, sorry for the late reply, the minimum spixel_size is 16 due to memory alignment and my laziness. if you need smaller superpixels, I would suggest you resize the image, segment at spixel_size = 16 then resize the mask back. 

The "orphan" superpixel issue, I will look into it. it should ideally remove the very small superpxiels.

**Comment by xjtuljy** [comment]
Does the "GIVEN_NUM" option have the same problem?

**Comment by carlren** [comment]
On Mon, Feb 15, 2016 at 12:59 PM, xjtuljy notifications@github.com wrote:

> problem

​If your (image_width x image_height)​ / num_of_spixel < 16 x 16 then it
will have the same problem of spixel_size <16.

---

Carl Yuheng Ren (PhD - Oxford, BSc - Harbin Institute of Technology)
Computer Vision Research Scientist @ Fyusion, Inc.
E-mail: carl@robots.ox.ac.uk  or _ren@carlyuheng.com ren@carlyuheng.com_
Cell Phone:+1 (415) 246 - 6665
Website: http://www.carlyuheng.com

---

任禹衡
计算机视觉高级研究员@Fyusion, Inc.
牛津大学工程学博士
哈尔滨工业大学计算机科学与技术学士
电话：+1 (415) 246 - 6665
邮箱：ren@carlyuheng.com 或 carl@robots.ox.ac.uk
网站:  http://www.carlyuheng.com

---

**Comment by xjtuljy** [comment]
Thank you very much for your reply @carlren . In my project, I do need to set a very high Given_num and doing everything in real-time. So is there any other way to lower this lower spixel_size limit (say 7x7), without doing image resize?

**Comment by carlren** [comment]
it depends on how big your image is, you can always rescale the image to
bigger, use 16x16 then scale the mask/image back to smaller resolution.

---

Carl Yuheng Ren (PhD - Oxford, BSc - Harbin Institute of Technology)
Computer Vision Research Scientist @ Fyusion, Inc.
E-mail: carl@robots.ox.ac.uk  or _ren@carlyuheng.com ren@carlyuheng.com_
Cell Phone:+1 (415) 246 - 6665
Website: http://www.carlyuheng.com

---

任禹衡
计算机视觉高级研究员@Fyusion, Inc.
牛津大学工程学博士
哈尔滨工业大学计算机科学与技术学士
电话：+1 (415) 246 - 6665
邮箱：ren@carlyuheng.com 或 carl@robots.ox.ac.uk
网站:  http://www.carlyuheng.com

---

**Comment by xjtuljy** [comment]
I see. Thanks again for your code and help!

**Comment by RyanCV** [comment]
However, the `Draw_Segmentation_Result` has no definition in gSLICr_seg_engine.cpp, how does it work?? thanks.

**Comment by carlren** [comment]
@RyanCV  
https://github.com/carlren/gSLICr/blob/master/gSLICr_Lib/engines/gSLICr_seg_engine_shared.h#L136

this is where you want to look at.
